### ISSUE TITLE
Bazzar view is broken

### ISSUE THREAD

**Issue by itamarhaber** [redis-stack/redis-stack-website#40]
* All licenses are other
* No stars shown
* Sorting is unclear
* No indication of recommended clients

**Comment by gkorland** [comment]
![image](https://user-images.githubusercontent.com/753206/187079236-80c03358-7cbd-4b2d-b347-a9daabb7b2e8.png)

**Comment by gkorland** [comment]
![image](https://user-images.githubusercontent.com/753206/187079249-68ad1d09-aaa9-4bdb-844c-ef7766abb3af.png)

**Comment by gkorland** [comment]
![image](https://user-images.githubusercontent.com/753206/187079274-f990bbf8-c008-4d83-976e-273755f2bf54.png)

**Comment by gkorland** [comment]
![image](https://user-images.githubusercontent.com/753206/187079324-de2666fe-6685-427b-9113-9536370ba55f.png)
